---

- name: lookup protected key, token set
  include_tasks: tasks/http-dump.yml
  vars:
    lookup_string: "{{ lookup('consul_test_kv_default_get_option',consul_key , \
      host=consul_host , \
      scheme=consul_scheme ,\
      port=consul_port, \
      token=consul_token) }}"

- name: lookup protected key, token not set
  include_tasks: tasks/http-dump.yml
  vars:
    lookup_string: "{{ lookup('consul_test_getoption_kv',consul_key , \
      host=consul_host , \
      scheme=consul_scheme ,\
      port=consul_port, \
      ) }}"      

- name: lookup public key, token not set  
  include_tasks: tasks/http-dump.yml
  vars:
    lookup_string: "{{ lookup('consul_test_getoption_kv',consul_key_public , \
      host=consul_host , \
      scheme=consul_scheme ,\
      port=consul_port, \
      ) }}"


- name: lookup public key, token set anyway  
  include_tasks: tasks/http-dump.yml
  vars:
    lookup_string: "{{ lookup('consul_test_getoption_kv',consul_key_public , \
      host=consul_host , \
      scheme=consul_scheme ,\
      port=consul_port, \
      token=consul_token) }}"

